#!/bin/sh
# Serial console listener: SBCL is the user-visible operating environment.
# init(8) respawns this in place of getty on constty.
export HOME=/root
export USER=root
export PATH=/usr/pkg/bin:/bin:/sbin:/usr/bin:/usr/sbin
export LD_LIBRARY_PATH=/usr/pkg/lib
export TERM=vt100
cd /root || cd /
exec /usr/pkg/bin/sbcl --noinform --no-sysinit --no-userinit --disable-debugger \
    2>>/var/log/lispbsd-console.log
